#Variables
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Ijc3MGRuNzcwQGdtYWlsLmNvbSIsInRpbWVzdGFtcCI6MTcwMzA2MzAxMzQ3MSwiaWF0IjoxNzAzMDYzMDEzLCJleHAiOjg2NTcwMzA2MzAxM30.AI1aNemkNW6m8kb18smfk7gKssP-KHi6cYP37Sy2jis
@name=test
@desc=rest.api
###################################
##### board CRUD

### create board
POST http://127.0.0.1:3000/board/create
Authorization: {{token}}
content-type: application/json

  {"name": "nnnn" ,"description": "{{desc}}","users": ["65781261eab8c3139b9845b0","6570622586d04dbba2bbfbce","6582a7fcf7057e9757b6d51d"]}        
###read board
GET http://127.0.0.1:3000/board/6582e82ce86c3858a9469ff8/read
Authorization: {{token}}

### read list of boards by userID
GET http://127.0.0.1:3000/board/user/65781261eab8c3139b9845b0/read
Authorization: {{token}}

### change title, description of board
PATCH  http://127.0.0.1:3000/board/6582e82ce86c3858a9469ff8/update
Authorization: {{token}}
content-type: application/json

{"name": "??", "description":"test"}

### change user's list of board
PATCH  http://127.0.0.1:3000/board/6582e82ce86c3858a9469ff8/update/users
Authorization: {{token}}
content-type: application/json

{"users": ["65781261eab8c3139b9845b0","6582a7fcf7057e9757b6d51d"]}
### add user to board
PATCH  http://127.0.0.1:3000/board/6582e4773aa9bffc5d4d62c3/update/users/add
Authorization: {{token}}
content-type: application/json

{"userId":"65781261eab8c3139b9845b0"}

### remove user to board
PATCH http://127.0.0.1:3000/board/6582e82ce86c3858a9469ff8/update/users/remove
Authorization: {{token}}
content-type: application/json

{"userId":"656598dd749f65404dcc2950"}


### remove board
DELETE http://127.0.0.1:3000/board/6582e4173aa9bffc5d4d62c1/delete
Authorization: {{token}}

###################################
### task CRUD

###create task
POST http://127.0.0.1:3000/board/6582e82ce86c3858a9469ff8/task/create
Authorization: {{token}}
content-type: application/json

{
   "name": "task",
   "description": "Task Description",
   "user": "netanel"
}

### read task
GET http://127.0.0.1:3000/board/6582e82ce86c3858a9469ff8/task/658954fc4dea2ae189040fc8/read
Authorization: {{token}}
 
### update task's title, description
PATCH  http://127.0.0.1:3000/board/6582e82ce86c3858a9469ff8/task/658954fc4dea2ae189040fc8/update
Authorization: {{token}}
content-type: application/json

{
   "name": "nt",
   "description": "Ta"
} 
### update list of users for task
PATCH  http://127.0.0.1:3000/board/6582e82ce86c3858a9469ff8/task/658958214dea2ae18904105f/update/users
Authorization: {{token}}
content-type: application/json

{"user": "65781261eab8c3139b9845b0"} 

### update status of task
PATCH  http://127.0.0.1:3000/board/6582e82ce86c3858a9469ff8/task/658958214dea2ae18904105f/update/status
Authorization: {{token}}
content-type: application/json

{"status": "Open" } 

### delete task
DELETE  http://127.0.0.1:3000/board/6582e82ce86c3858a9469ff8/task/6589697c91dc610a68400fbc/delete
Authorization: {{token}}

###################################
### comment CRUD

###create comment
POST http://127.0.0.1:3000/comment/create

### read comment
POST http://127.0.0.1:3000/comment/:commentId/read

### edit comment
PATCH  http://127.0.0.1:3000/comment/:commentId/update


### delete comment
PATCH  http://127.0.0.1:3000/comment/:commentId/delete

##############################
### users API

### list of all users detailes
GET http://127.0.0.1:3000/users/all
Authorization: {{token}}

### find user details by token
GET  http://127.0.0.1:3000/users/self
Authorization: {{token}}

### return list of users details in the list of task/board
GET http://127.0.0.1:3000/users/in
Authorization: {{token}}
content-type: application/json

{
  "boardID": "6582e82ce86c3858a9469ff8"
}
### return list of users details that not in the list of task/board
GET  http://127.0.0.1:3000/users/ex
Authorization: {{token}}
content-type: application/json

{
  "boardID": "6582e82ce86c3858a9469ff8"
}


################################